[package]
name = "newsletter"
version = "0.1.0"
authors = ["angelo catalani <catalaniangelo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "=4.0.0-beta.3"
