[package]
name = "newsletter"
version = "0.1.0"
authors = ["angelo catalani <catalaniangelo@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "newsletter"

[dependencies]
actix-web = "=4.0.0-beta.3"

[dev-dependencies]
actix-rt = "~2.0"
reqwest = "~0.11"
tokio = {version= "~1.3.0", features = ["rt", "net"] }
