name: newsletter
region: fra

databases:
  - engine: PG
    name: newsletter-database
    num_nodes: 1
    size: db-s-dev-database
    version: "12"

services:
  - http_port: 8000
    image:
      registry_type: DOCR
      repository: newsletter
      tag: <TAG>
    instance_count: 1
    instance_size_slug: basic-xs
    name: newsletter
    routes:
      - path: /

envs:
  - key: APP_DATABASE__NAME
    scope: RUN_TIME
    value: ${newsletter-database.DATABASE}
  - key: APP_DATABASE__HOST
    scope: RUN_TIME
    value: ${newsletter-database.HOSTNAME}
  - key: APP_DATABASE__PASSWORD
    scope: RUN_TIME
    value: ${newsletter-database.PASSWORD}
  - key: APP_DATABASE__PORT
    scope: RUN_TIME
    value: ${newsletter-database.PORT}
  - key: APP_DATABASE__USERNAME
    scope: RUN_TIME
    value: ${newsletter-database.USERNAME}