[application]
host = "127.0.0.1"
max_pending_connections = 128
port = 8000

[database]
connect_timeout_seconds = 2
database_name = "newsletter"
host = "localhost"
max_db_connections = 16
password = "password"
port = 9000
require_ssl = false
username = "postgres"
