[application]
max_pending_connections = 128
port = 8000

[database]
connect_timeout_seconds = 2
database_name = "newsletter"
host = "localhost"
password = "password"
port = 9000
username = "postgres"
max_db_connections = 16
