[application]
max_pending_connections = 128
port = 8000

[database]
connect_timeout_seconds = 2
name = "newsletter"
host = "localhost"
max_db_connections = 16
password = "password"
port = 9000
require_ssl = false
username = "postgres"

[email_client]
base_url = "https://api.postmarkapp.com"
sender_email = "testemail@gmail.com"
token = "test-secret-token"
timeout_secs = 10
