name: Scheduled Deploy
on:
  schedule:
    - cron: '0 0 30 4 *' # at 00:00 on day-of-month 30 in April
env:
  app_name: newsletter
  docker_registry: angeloft
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@main
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 3600
      - name: Build container image
        run: docker build -t registry.digitalocean.com/${{ env.docker_registry }}/${{ env.app_name }}:$(echo $GITHUB_SHA | head -c7) .
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/${{ env.docker_registry }}/${{ env.app_name }}:$(echo $GITHUB_SHA | head -c7)
      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's/<TAG>/'"$TAG"'/' $GITHUB_WORKSPACE/spec.yaml
      - name: Deploy to DigitalOcean Apps
        run: doctl apps create-deployment $(doctl apps list --format ID --no-header) --wait true
